Document: haproxy-auth-request
Title: Debian haproxy-auth-request Manual
Author: <insert document author here>
Abstract: This manual describes what haproxy-auth-request is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/haproxy-auth-request/haproxy-auth-request.sgml.gz

Format: postscript
Files: /usr/share/doc/haproxy-auth-request/haproxy-auth-request.ps.gz

Format: text
Files: /usr/share/doc/haproxy-auth-request/haproxy-auth-request.text.gz

Format: HTML
Index: /usr/share/doc/haproxy-auth-request/html/index.html
Files: /usr/share/doc/haproxy-auth-request/html/*.html
